app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
use App\User;
use Illuminate\Http\Request;


// temp get logout route updating from 5.2 to 5.3
Route::get('/logout', 'Auth\LoginController@logout');
Route::auth();

Route::resource('users', 'UserController');

Route::get('/', 'ProjectsController@index')->name('project.list');
Route::get('/{slug}/edit', 'ProjectsController@edit')->name('project.edit');
Route::get('/project/new', 'ProjectsController@create')->name('project.create');
Route::match(['put', 'post'], '/project/update/{id?}', 'ProjectsController@update')->name('project.update');

Route::get('/{slug}', 'IssueController@index' )->name('project');
Route::get('/{slug}/issue/new', 'IssueController@create' )->name('issue.create');
Route::get('/{slug}/issue/{number}/edit', 'IssueController@edit' )->name('issue.edit');
Route::get('/{slug}/issue/{number}/watch', 'IssueController@watch' )->name('issue.watch');
Route::get('/{slug}/issue/{number}/unwatch', 'IssueController@unwatch' )->name('issue.unwatch');

Route::match(['put', 'post'], '/{slug}/issue/update/{id?}', 'IssueController@update')->name('issue.update'); // 'IssueController@update')->name('issue.update');
Route::get('/{slug}/issue/{number}', 'IssueController@view' )->name('issue');
Route::post('/{slug}/issue/{issueid}/label/create', 'IssueController@createLabel' )->name('issue.createlabel');
Route::post('/{slug}/issue/{issueid}/label/{labelid}', 'IssueController@toggleLabel' )->name('issue.togglelabel');

Route::post('/{slug}/md/preview', 'CommentController@preview' )->name('comment.preview');
Route::post('/{slug}/issue/{issueid}/comment/create', 'CommentController@create')->name('comment.add');
Route::put('/comment/{commentid}', 'CommentController@update')->name('comment.update');



/**
 * TODO: find a proper way to manage avatars
 */


Route::get('/avatar/{userid}-{size}.png', function ($userid, $size) {
    $filesize="-$size";
    $file = public_path()."/avatar/$userid$filesize.png";

    header("Content-type: image/png");
    header("Cache-control: public, max-age=3600");


    if (is_file($file)) {
        echo file_get_contents($file);
    } else {
        $requiredsize=(int)$size;
        $nstripes = 4;


        $user = \App\User::findOrFail($userid);
        //~ $hash = md5(rand());
        $hash = md5($user->email);
        // #30fda0 #9ea8ea #f34345 #3876c7 #34c450 fe
        $colors = substr($hash, 0, $nstripes*6);
        $grad = (hexdec(substr($hash, 30, 2)) / 255) * 360;


        $size = $requiredsize * 1.414213562;
        $step = $size / $nstripes;


        $im = imagecreatetruecolor($size, $size);
        for($stripe=0; $stripe<$nstripes; $stripe++) {
            $color = imagecolorallocate($im,
                hexdec(substr($colors, 6*$stripe, 2)),
                hexdec(substr($colors, 6*$stripe+2,2)),
                hexdec(substr($colors, 6*$stripe+4,2))
            );
            imagefilledrectangle($im,
                0 , $step * $stripe,
                $size, $step * $stripe + $step,
                $color
            );
        }

        $im = imagerotate($im, $grad, $color);

        $center = imagesx($im) / 2;
        $hsize = $requiredsize / 2;
        //~ imagerectangle($im,
            //~ $center-$hsize, $center-$hsize,
            //~ $center+$hsize, $center+$hsize,
            //~ 0
        //~ );
        $im = imagecrop($im, [
            "x" => $center-$hsize,
            "y" => $center-$hsize,
            "width" => $requiredsize,
            "height" => $requiredsize
        ]);

        //~ if (hexdec(substr($colors, 30, 2)) % 2 ) {
            //~ $im = imagerotate($im, 90, $color);
        //~ }

        imagepng($im, $file);
        imagepng($im);
        imagedestroy($im);
    }
    die();
})->name('avatar')->where('userid', '[0-9]+')->where('size', '[0-9]+');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Contracts\Support\Htmlable as HtmlableContract;

use Ultraware\Roles\Traits\HasRoleAndPermission;
use Ultraware\Roles\Contracts\HasRoleAndPermission as HasRoleAndPermissionContract;

use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements HasRoleAndPermissionContract, HtmlableContract
{
    use HasRoleAndPermission;
    use Notifiable;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    /**
     * Get the issues created by the user.
     */
    public function issues()
    {
        return $this->hasMany('App\Issue');
    }

    /**
     * Get the issues user is subscribed to.
     */
    public function subscribtions()
    {
        return $this->hasMany('App\Issue', 'issue_subscribers');
    }

    /**
     * Is user subscribed to issue id
     *
     * @param App\Issue $issue
     * @return bool
     */
    public function isSubscribedTo(Issue $issue)
    {
        return $this->subscribtions()->where('id', $issue->id)->count() > 0;
    }


    /**
     * Get the comments created by the user.
     */
    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

    /**
     * Get the projects this user can access
     */
    public function projects()
    {
        return $this->belongsToMany('App\Project', 'project_user');
    }

    public function toHtml()
    {
        return "@".$this->username;
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Hash;
use Illuminate\Http\Request;

use App\Http\Requests\AdminRequest;
use App\Http\Requests\NewUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\User;

class UserController extends Controller
{
    protected $roles;
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $roles =  app(config('roles.models.role'))->all();

        $this->roles = [];
        foreach($roles as $role) $this->roles[$role->id] = $role->name;

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(AdminRequest $request)
    {
        return view('user.index', ['users'=>User::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(AdminRequest $request)
    {
        return view('user.create',['user'=>null, 'roles'=>$this->roles]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(NewUserRequest $request)
    {
        $credentials = [
            'name' => $request->input('name'),
            'username' => $request->input('username'),
            'email' => $request->input('email'),
            'password' => $request->input('password')
        ];
        $credentials['password'] = Hash::make($credentials['password']);
        try {
            $user = User::create($credentials);
        } catch (Exception $e) {
            $request->session()->flash('alert', ['type'=>'error', 'message'=>'User already exists']);
            return redirect()->route('users.list');
        }

        $request->session()->flash('alert', ['type'=>'success', 'message'=>'User created']);
        return redirect()->route('users.edit', $user->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(AdminRequest $request, $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(AdminRequest $request, $id)
    {
        return view('user.edit',['user'=>User::findOrFail($id), 'roles'=>$this->roles]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, $id)
    {
        $message = "User saved";
        $user = User::findOrFail($id);
        $user->name = $request->input('name');
        $user->username = $request->input('username');
        $user->email = $request->input('email');
        $password = $request->input('password');
        if ($password !== "") {
            $user->password = Hash::make($password);
            $message .= ", password updated";
        }

        $user->roles()->sync($request->input('roles', []));

        $user->save();

        $request->session()->flash('alert', ['type'=>'success', 'message'=>$message]);
        return redirect()->route('users.edit', $user->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(AdminRequest $request, $id)
    {
        //
    }
}

resources/views/user/base.blade.php
@extends('layouts.app')

@section('nav.users', 'active')

@section('title')
 - Users
@endsection

@section('nav')
    <li><a href="{{ url('/') }}" class="active">Projects</a></li>
@endsection

resources/views/user/create.blade.php
@extends('user.form')

@section('form.title')
    Users - New user
@endsection

resources/views/user/edit.blade.php
@extends('user.form')

@section('form.title')
    Users - Edit #{{ $user->id }}
@endsection

resources/views/user/form.blade.php
@extends('user.base')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                {!! BootForm::open(['model' => $user, 'store' => 'users.store', 'update' => 'users.update']) !!}
                    <div class="panel-heading">
                        <h3 class="panel-title">@yield('form.title')</h3>
                    </div>
                    <div class="panel-body">
                        {!! BootForm::text('name') !!}
                        {!! BootForm::text('username') !!}
                        {!! BootForm::email('email') !!}
                        {!! BootForm::password('password') !!}
                        {!! BootForm::password('password_confirmation', 'Confirm password') !!}

                        {!! BootForm::checkboxes('roles[]', "User role", $roles, (($user) ? $user->roles()->pluck('role_id')->toArray():[]) ) !!}
                    </div>
                    <div class="panel-footer">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                {!! BootForm::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('user.base')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Users
                        <a class="pull-right btn btn-default btn-xs"
                         href="{{ route('users.create') }}" title="Add new user">
                            <i class="fa fa-user-plus"></i>
                        </a>
                    </div>

                    <!-- <div class="panel-body">

                    </div> -->
                    <ul class="list-group">
                    @foreach($users as $user)
                        <li class="list-group-item">
                            <a href="{{ route("users.edit", $user->id) }}">
                                <img src="{{ route('avatar', [$user->id, 16]) }}" width="16" height="16">
                                {{ $user->name }}
                                <span class="text-muted">{{ $user }}</span>
                            </a>
                            <span class="pull-right">
                                @if($user->hasRole('admin'))
                                        <i class="fa fa-key" title="administrator"></i>
                                @endif
                                <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash" title="Delete user"></i></a>
                            </span>
                        </li>
                    @endforeach
                    </ul>
                </div>
            </div>
        </div>
    </div>
@endsection